### ISSUE TITLE
Software auf Stift laden - unklar

### ISSUE THREAD

**Issue by bjoernmichels** [gysibnc/Architekturdokumentation-TipToi#11]
Auf was bezieht sich der UseCase `Software auf Stift laden`
a) auf die Firmware? -> dann sollte der UseCase `Firmware aktualisieren` heissen.
b) auf die Audionfiles? -> dann sollte der UseCase `Audiodatei laden` heissen
c) braucht es a) und b) ?

![image](https://user-images.githubusercontent.com/47139880/156065005-f6af3e8c-cf75-4f51-b814-899abb5379a1.png)

**Comment by bjoernmichels** [comment]
c) :smile:

![image](https://user-images.githubusercontent.com/47139880/156436057-5d6c6bb5-f6ed-40c9-898b-703977747e2c.png)

**Comment by n1c30n3** [comment]
Software auf den Stift laden wurde nun etwas besser umschrieben ;)
