### ISSUE TITLE
Kommentare zum UseCase-Diagramm

### ISSUE THREAD

**Issue by bjoernmichels** [gysibnc/Architekturdokumentation-TipToi#4]
![image](https://user-images.githubusercontent.com/47139880/155397440-1ecbea35-9ae1-4e3d-b9db-73ae62f3627c.png)

1. Das UseCase Diagramm sieht sehr gut aus.
2. Das UseCase Diagramm beschreibt den `tiptoi Stift`.
3. Es fehlt der `tiptoi Manager` als Aktor. Dieser hätte auch eine Verbindung zum UseCase `Software auf den Stift laden`
4. Die UseCases für das `Kind` liessen sich vereinfachen zB in `Spielen` und `Hörbücher hören`... oder auch nur `Spielen`.
5. Die UseCases für das `Kind` haben eine Verbindung zum `tiptoi Produkt`.
6. Der `Entwickler` hat den UseCase `OID-Debug-Funktion nutzen` (und der UseCase hat eine Verbindung zum `toitoi Produkt`).

**Comment by bjoernmichels** [comment]
Das UseCase Diagramm sieht sehr gut aus!

1. Für den UseCase `Software auf den Stift laden` benötigt es auch den Aktor `Eltern`.  Also auch hier eine Assoziation. 
2. `TipToi Manager bedienen` ist kein UseCase des `TipToi Stift` denn der `TipToi Stift` hat ja keinen Einfluss auf die Softwareanwendung `TipToi Manager` auf dem PC. Für den `TipToi Manager` würde sich ein eigenes UseCase Diagramm anbieten.
3. Die UseCases `Buch initial scannen`, `Hörbücher hören`, `Spielen` haben auch je eine Assoziation mit dem `ToiToi Produkt`, denn der Stift soll ja Scannen.

![image](https://user-images.githubusercontent.com/47139880/156059103-c90558a6-f85f-4d61-afbe-27b8053baba3.png)

**Comment by n1c30n3** [comment]
Anpassungsvorschläge wurden integriert.

**Comment by n1c30n3** [comment]
Bei Punkt drei teilen wir deine Meinung nicht. 
Das TipToi-Produkt ist Bsp. ein Buch, das führt nichts aus, es hört keine Hörbücher und spielt nicht. 
Aus diesem Grund haben wir diesen Punkt weggelassen.

**Comment by bjoernmichels** [comment]
Die Assoziation (Linie zwischen Aktor und UseCase) sagt lediglich aus, ob welche Aktoren in einem UseCase beteiligt sind. Nicht aber wer den UseCase auslöst / aktiv oder passiv ist.

Beispiel:
Bei `Audiofile laden` wissen wir nicht wer zuerst aktiv wird. Vielleiht der Aktor `Eltern`. Beschrieben wird in der UseCase Beschreibung: https://de.wikipedia.org/wiki/Anwendungsfall#Aufbau_eines_Anwendungsfalls 
![image](https://user-images.githubusercontent.com/47139880/156446369-81010d8a-2df2-461e-81d4-3bfb4fda0324.png)
